### ISSUE TITLE
I2C running at 1/10th the frequency setting

### ISSUE THREAD

**Issue by osterwood** [therealprof/stm32f4xx-hal#26]
Hi,

I'm using this HAL with an STM32F401RE MCU and have run into an issue with I2C configuration. Tried a few different parameters for i2c1 speed (setting -> observed):
* 10 kHz -> 8.7 kHz
* 20 kHz -> 17.4 kHz
* 40 kHz -> 34.7 kHz
* 60 kHz -> 6.45 kHz
* 100 kHz -> 7.5 kHz
* 200 kHz ->11.5 kHz
* 400 kHz -> 23.6 khz
* 1600 kHz -> 94.7 kHz

My delay provider does work correctly, however. `delay.delay_ms(100_u16);` measures at 99.7 ms.

Any idea why SCL runs at 1/10th (or less) the speed of the setting?  Also, I'm running the MCU at 40 MHz, which could relate to the change in mapping after 40 kHz.

**Comment by psycowithespn** [comment]
I've created a PR that seems to fix these issues, #34.
